### ISSUE TITLE
Can you please make this for Ubuntu with K v5.4.7?

### ISSUE THREAD

**Issue by abhisek176** [ppaulweber/linux-mba#1]

**Comment by ppaulweber** [comment]
Hello @abhisek176, as far as I know, most of the patches already made it upstream in the latest Linux kernel. I'll try ASAP to check the status of that, but the T2 bridge driver has to be included no matter what. If it works for my setup, then Ubuntu should work as well, you just have to config properly the kernel and ramfs in your bootloader setting.

**Comment by abhisek176** [comment]
It seems the touchpad scrolling, right click and taps not working. Everything else is fine.

**Comment by ppaulweber** [comment]
In this case the appropriate patch for `hid` and `bcm5974` is missing in the kernel for your system. What version of the MBA/MBP do you have? Can you find out your USB ids from the keyboard and touchpad?

**Comment by abhisek176** [comment]
MBP 15,4

**Comment by ppaulweber** [comment]
Ok, and what are the USB device ids? You can find out via `lsusb -v | grep Bus`.

**Comment by abhisek176** [comment]
[
[usb.txt](https://github.com/ppaulweber/linux-mba/files/4025899/usb.txt)
](url)

**Comment by ppaulweber** [comment]
I've just checked the upstream Linux kernel `v5.4.7` and sadly there is no support of your USB device id for the keyboard and trackpad ... you have to patch the kernel yourself.

**Comment by abhisek176** [comment]
Now I use kernel 5.5.rc5. Can you check this ?

**Comment by ppaulweber** [comment]
Your USB device id is still not in this upstream kernel.

**Comment by abhisek176** [comment]
But I am able to make all things work except right click and scroll functions on touchpad. Can you tell me how can I add the id?

**Comment by ppaulweber** [comment]
You would have to patch the kernel source files `drivers/input/mouse/bcm5974.c` and `drivers/hid/hid-{ids.h,apple.c,quirks.c}`. I can prepare a patch for you ASAP I've successfully tested the latest version on my MBA.

**Comment by abhisek176** [comment]
Thank you. please let me know.

**Comment by abhisek176** [comment]
I see that there is an input of MBP15,4 in the bcm5974.c file in 5.5-rc5 kernel. Also, the same architecture input is in hid-apple.c.

**Comment by ppaulweber** [comment]
> I see that there is an input of MBP15,4 in the bcm5974.c file in 5.5-rc5 kernel. Also, the same architecture input is in hid-apple.c.

@abhisek176 I assume (based on the `lsusb` output provided by you) the USB device ID for your system is `05ac:027d` and when I make a quick look and `grep` through the Linux kernel sources at your desired version `5.5-rc5` there is nothing defined yet for your system:

~~~
$ LINUX_SOURCES=https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree
$ curl -s $LINUX_SOURCES/drivers/hid/hid-ids.h?h=v5.5-rc5 | grep 0x027
<span class="cp">#define USB_DEVICE_ID_APPLE_WELLSPRING9_ANSI	0x0272</span>
<span class="cp">#define USB_DEVICE_ID_APPLE_WELLSPRING9_ISO	0x0273</span>
<span class="cp">#define USB_DEVICE_ID_APPLE_WELLSPRING9_JIS	0x0274</span>
~~~

~~~
$ LINUX_SOURCES=https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree
$ curl -s $LINUX_SOURCES/drivers/input/mouse/bcm5974.c?h=v5.5-rc5 | grep 0x027
<span class="cp">#define USB_DEVICE_ID_APPLE_WELLSPRING9_ANSI	0x0272</span>
<span class="cp">#define USB_DEVICE_ID_APPLE_WELLSPRING9_ISO	0x0273</span>
<span class="cp">#define USB_DEVICE_ID_APPLE_WELLSPRING9_JIS	0x0274</span>
~~~

~~~
$ LINUX_SOURCES=https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree
$ curl -s $LINUX_SOURCES/drivers/hid/hid-apple.c?h=v5.5-rc5 | grep 0x027
<no output at all>
~~~

As you can see, only USB devices IDs for `..:0272`,  `..:0273`, and  `..:0274` are in this specific Linux kernel version available so far.
